# Generated by Codex on 2026-07-16

# Django
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def _backfill_tracking_events(apps, schema_editor) -> None:
    """
    Seed tracking history for existing FAT rows.
    """

    fat_model = apps.get_model("afat", "Fat")
    tracking_event_model = apps.get_model("afat", "FatTrackingEvent")
    db_alias = schema_editor.connection.alias

    existing_fat_ids = set(
        tracking_event_model.objects.using(db_alias).values_list("fat_id", flat=True)
    )
    events_to_create = []

    fats = fat_model.objects.using(db_alias).select_related("fatlink").iterator()

    for fat in fats:
        if fat.id in existing_fat_ids:
            continue

        events_to_create.append(
            tracking_event_model(
                fat_id=fat.id,
                observed=fat.fatlink.created,
                event="JOIN",
                solar_system_id=fat.solar_system_id,
                ship_id=fat.ship_id,
                source="legacy",
            )
        )

    tracking_event_model.objects.using(db_alias).bulk_create(
        events_to_create, batch_size=1000
    )


class Migration(migrations.Migration):

    dependencies = [
        ("afat", "0003_alliance_auth_proxy_models"),
        ("eve_sde", "0018_blueprintactivity_blueprintactivityproduct_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FatTrackingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observed",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When this tracking event was observed",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("JOIN", "Joined fleet"),
                            ("LEAVE", "Left fleet"),
                            ("SYSTEM_CHANGE", "Changed system"),
                            ("SHIP_CHANGE", "Changed ship"),
                            ("SYS_SHIP_CHANGE", "Changed system and ship"),
                        ],
                        db_index=True,
                        help_text="What changed for this pilot",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("esi", "ESI"),
                            ("clickable", "Clickable FAT"),
                            ("manual", "Manual FAT"),
                            ("snapshot", "Fleet snapshot"),
                            ("legacy", "Legacy FAT"),
                        ],
                        db_index=True,
                        default="esi",
                        help_text="Where this tracking event came from",
                        max_length=16,
                    ),
                ),
                (
                    "fat",
                    models.ForeignKey(
                        help_text="The FAT this tracking event belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="afat.fat",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        blank=True,
                        help_text="The ship the character was flying for this event",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.itemtype",
                    ),
                ),
                (
                    "solar_system",
                    models.ForeignKey(
                        blank=True,
                        help_text="The system the character was in for this event",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.solarsystem",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAT tracking event",
                "verbose_name_plural": "FAT tracking events",
                "default_permissions": (),
                "ordering": ("observed", "id"),
                "indexes": [
                    models.Index(
                        fields=["fat", "observed"],
                        name="afat_fattrac_fat_id_00fdd9_idx",
                    ),
                    models.Index(
                        fields=["fat", "event"],
                        name="afat_fattrac_fat_id_39c7f5_idx",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            code=_backfill_tracking_events,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
