# Generated by Codex on 2026-07-16

# Django
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afat", "0004_fat_tracking_events"),
        ("authentication", "0026_alter_characterownership_user_and_more"),
        ("eveonline", "0019_v5squash"),
    ]

    operations = [
        migrations.CreateModel(
            name="EsiFleetAutoTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether automatic fleet tracking is enabled for this character",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When automatic fleet tracking was enabled",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this automatic fleet tracking setting was last updated",
                    ),
                ),
                (
                    "character",
                    models.OneToOneField(
                        help_text="The character whose fleets should be automatically tracked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="afat_esi_fleet_auto_tracking",
                        to="eveonline.evecharacter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who enabled automatic fleet tracking",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="afat_esi_fleet_auto_tracking",
                        to="authentication.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "ESI fleet auto tracking",
                "verbose_name_plural": "ESI fleet auto tracking",
                "default_permissions": (),
                "ordering": ("character__character_name",),
            },
        ),
    ]
