# Generated by Codex on 2026-07-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("afat", "0005_esi_fleet_auto_tracking"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "permissions": (
                    (
                        "basic_access",
                        "Can access the AFAT module",
                    ),
                    (
                        "manage_afat",
                        "Can manage the AFAT module",
                    ),
                    (
                        "add_fatlink",
                        "Can create FAT links",
                    ),
                    (
                        "stats_corporation_own",
                        "Can see own corporation statistics",
                    ),
                    (
                        "stats_corporation_other",
                        "Can see statistics of other corporations",
                    ),
                    (
                        "log_view",
                        "Can view the modules log",
                    ),
                    (
                        "inspector",
                        "Can inspect FAT tracking events",
                    ),
                ),
                "verbose_name": "AFAT",
            },
        ),
    ]
