# Generated by Django 5.2.17 on 2026-08-15 18:50

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afat", "0006_add_inspector_permission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("basic_access", "Can access the AFAT module"),
                    ("manage_afat", "Can manage the AFAT module"),
                    ("add_fatlink", "Can create FAT links"),
                    (
                        "stats_corporation_own",
                        "Can see own corporation statistics",
                    ),
                    (
                        "stats_corporation_other",
                        "Can see statistics of other corporations",
                    ),
                    ("log_view", "Can view the modules log"),
                    ("inspector", "Can inspect FAT tracking events"),
                ),
                "verbose_name": "AFAT",
            },
        ),
        migrations.AlterField(
            model_name="esifleetautotracking",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="fattrackingevent",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
